### PR TITLE
irem/closePR

### PR DESCRIPTION
**Pull request by vIremAydin**

### CODE REVIEW

**Comment by vIremAydin** [comment]
**ACTIVE**: <p>heloo<em> <u>fczvcfcv</u></em></p>

**Comment by vIremAydin** [comment]
> **ACTIVE**: <p>heloo<em> <u>fczvcfcv</u></em></p>
> https://github.com/hubreviewapp/hubreview/pull/185#issuecomment-2068067742

**Comment by vIremAydin** [comment]
> **ACTIVE**: <p>heloo<em> <u>fczvcfcv</u></em></p>
> https://github.com/hubreviewapp/hubreview/pull/185#issuecomment-2068067742 

no help dsjksdfjd

**Comment by AlperMumcular** [comment]
**ACTIVE**: <p>hello</p>

**Pull request merged**
