### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AlperMumcular**

### CODE REVIEW

**Review by AlperMumcular — COMMENTED** [review]
aaaa

**Review by AlperMumcular — COMMENTED** [review]
aasda

**Review by AlperMumcular — COMMENTED** [review]
sadsaas

**Review by AlperMumcular — COMMENTED** [review]
DASSADS

**Comment by aysekelleci** [comment]
**ACTIVE**: <p>test</p>

**Comment by aysekelleci** [comment]
> **ACTIVE**: <p>test</p>
> https://github.com/hubreviewapp/hubreview/pull/84#issuecomment-2041433600 

reply test

**Comment by aysekelleci** [comment]
**ACTIVE**: <p>comment</p>

**Comment by aysekelleci** [comment]
> **ACTIVE**: <p>comment</p>
> https://github.com/hubreviewapp/hubreview/pull/84#issuecomment-2041440022 

reply2

**Pull request merged**
